version: 1

api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /css/images
  static_dir: css/images
- url: /js
  static_dir: js
- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
